# -*- coding: utf-8 -*-
"""# balance before split

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyrGo_46SoiCK0-4BfvJfxmbPVcAwVib

#Data Preprocessing
"""

pip install scikit-optimize

# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from imblearn.combine import SMOTEENN
from sklearn.feature_selection import mutual_info_classif, RFE
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from skopt import BayesSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import shap

# Load the dataset
df = pd.read_excel('C:/Users/User/Desktop/fyp/prototype/PCOS_data_without_infertility.xlsx')

# Convert column names to lowercase
df.columns = df.columns.str.lower()

print("Dataset's column names are in lowercase")

print(df.shape)

print("\nData types:")
print(df.dtypes)

# Original column names before any modifications
original_columns = df.columns.copy()

# Step 1: Strip leading and trailing spaces
df.columns = df.columns.str.strip()
stripped_cols = [orig for orig, new in zip(original_columns, df.columns) if orig != new]
if stripped_cols:
    print("Columns with stripped spaces:", stripped_cols)

# Step 2: Fix multiple spaces inside column names
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True)
fixed_spaces_cols = [orig for orig, new in zip(original_columns, df.columns) if orig != new]
if fixed_spaces_cols:
    print("Columns with fixed internal spaces:", fixed_spaces_cols)

# Step 3: Standardize encoding
df.columns = df.columns.str.encode('utf-8').str.decode('utf-8')
encoding_fixed_cols = [orig for orig, new in zip(original_columns, df.columns) if orig != new]
if encoding_fixed_cols:
    print("Columns with encoding fixes:", encoding_fixed_cols)

print(f"Number of rows before removing duplicates: {len(df)}")
df = df.drop_duplicates()
print(f"Number of rows after removing duplicates: {len(df)}")

# Drop redundant columns
df.drop(columns=['sl. no', 'patient file no.', 'unnamed: 44'], inplace=True)

print("Redundant columns dropped")

# Calculate missing percentage
missing_percentage = df.isnull().mean() * 100

# Identify columns with more than 30% missing values
columns_to_drop = missing_percentage[missing_percentage > 30].index

# Print the columns that will be dropped
print("Columns to be dropped due to more than 30% missing values:")
print(columns_to_drop)

# Drop identified columns
df.drop(columns=columns_to_drop, inplace=True)

print("\nColumns with more than 30% missing values dropped")

# Clean and convert 'ii beta-hcg(miu/ml)' and 'amh(ng/ml)' to float
df['ii beta-hcg(miu/ml)'] = pd.to_numeric(df['ii beta-hcg(miu/ml)'], errors='coerce')
df['amh(ng/ml)'] = pd.to_numeric(df['amh(ng/ml)'], errors='coerce')


# Check if the conversion was successful
print("Data types after conversion:")
print(df[['ii beta-hcg(miu/ml)', 'amh(ng/ml)']].dtypes)

# Convert columns to numeric and handle non-numeric values
numeric_cols = df.select_dtypes(include=[np.number]).columns
non_numeric_cols = df.select_dtypes(exclude=[np.number]).columns

# Convert non-numeric columns to numeric if possible, otherwise drop them
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Fill missing values in numeric columns with the mean
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Fill missing values in categorical columns with the mode
df[non_numeric_cols] = df[non_numeric_cols].apply(lambda col: col.fillna(col.mode()[0]))

# Print the number of missing values after handling
print("\nRemaining NaN values after handling:")
print(df.isnull().sum().loc[df.isnull().sum() > 0])  # Should print nothing if all NaNs are filled

# Encode categorical features
label_encoders = {}
for column in non_numeric_cols:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

print("Data encoded successfully")

# Address class imbalance
target_column = 'pcos (y/n)'
if target_column not in df.columns:
    raise KeyError(f"Target column '{target_column}' not found in the DataFrame")

smoteenn = SMOTEENN(random_state=42)
X_resampled, y_resampled = smoteenn.fit_resample(df.drop(target_column, axis=1), df[target_column])

print("Class imbalance addressed")

"""#Feature Selection Techniques"""

# Filter method: Mutual Information
mi_scores = mutual_info_classif(X_resampled, y_resampled)
mi_df = pd.DataFrame({'Feature': X_resampled.columns, 'MI_Score': mi_scores})
mi_df = mi_df.sort_values(by='MI_Score', ascending=False).head(30)

# Print the top 30 features based on Mutual Information
print("\nTop 30 features selected by Mutual Information:")
print(mi_df)

# Wrapper method: RFE
n_features_to_select = min(30, X_resampled.shape[1])  # Ensure n_features_to_select is not greater than the number of features
estimator = RandomForestClassifier(random_state=42)
selector = RFE(estimator, n_features_to_select=n_features_to_select)
selector = selector.fit(X_resampled, y_resampled)
rfe_df = pd.DataFrame({'Feature': X_resampled.columns, 'Rank': selector.ranking_})
rfe_df = rfe_df[rfe_df['Rank'] == 1]

# Print the top features selected by RFE
print("\nTop features selected by RFE:")
print(rfe_df)

# Embedded method: Tree-based
rf = RandomForestClassifier(random_state=42)
rf.fit(X_resampled, y_resampled)
importances = rf.feature_importances_
tree_df = pd.DataFrame({'Feature': X_resampled.columns, 'Importance': importances})
tree_df = tree_df.sort_values(by='Importance', ascending=False).head(30)

# Print the top 30 features selected by Tree-based method
print("\nTop 30 features selected by Tree-based:")
print(tree_df)

# Select top 30 features based on mutual_info
top_features_mi = mi_df['Feature'].tolist()
top_features_rfe = rfe_df['Feature'].tolist()
top_features_tree = tree_df['Feature'].tolist()

# Get common features across all methods
common_features = set(top_features_mi).intersection(set(top_features_rfe)).intersection(set(top_features_tree))
common_features = list(common_features)[:30]  # Ensure only 30 features

# Print the common features across all methods
print("\nCommon features across all methods:")
print(common_features)

"""#Splitting Dataset

"""

# Split using 80:20 ratio
X_train_80, X_test_80, y_train_80, y_test_80 = train_test_split(
    X_resampled[common_features], y_resampled, test_size=0.2, stratify=y_resampled, random_state=42)

# Print the shapes of the split datasets
print("80:20 Split:")
print(f"X_train_80 shape: {X_train_80.shape}")
print(f"X_test_80 shape: {X_test_80.shape}")
print(f"y_train_80 shape: {y_train_80.shape}")
print(f"y_test_80 shape: {y_test_80.shape}")

# Split using 70:30 ratio
X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(
    X_resampled[common_features], y_resampled, test_size=0.3, stratify=y_resampled, random_state=42)

# Print the shapes of the split datasets
print("70:30 Split:")
print(f"X_train_70 shape: {X_train_70.shape}")
print(f"X_test_70 shape: {X_test_70.shape}")
print(f"y_train_70 shape: {y_train_70.shape}")
print(f"y_test_70 shape: {y_test_70.shape}")



"""#Models Optimization and Training"""

# Define models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Support Vector Machine': SVC(probability=True),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
    'AdaBoost': AdaBoostClassifier(),
    'Naive Bayes': GaussianNB()
}

# Define parameter grids for each model
param_grids = {
    'Logistic Regression': {'C': (1e-6, 1e+6, 'log-uniform')},
    'Random Forest': {'n_estimators': (10, 200), 'max_depth': (1, 20)},
    'Decision Tree': {'max_depth': (1, 20)},
    'Naive Bayes': {},  # No hyperparameters to optimize
    'Support Vector Machine': {'C': (1e-6, 1e+6, 'log-uniform'), 'gamma': (1e-6, 1e+1, 'log-uniform')},
    'K-Nearest Neighbors': {'n_neighbors': (1, 30)},
    'XGBoost': {'n_estimators': (10, 200), 'max_depth': (1, 20), 'learning_rate': (1e-3, 1.0, 'log-uniform')},
    'AdaBoost': {'n_estimators': (10, 200)}
}

# Hyperparameter optimization using Bayesian Search
def bayesian_optimization(model, param_grid, X_train, y_train):
    if not param_grid:
        print(f"No hyperparameters to optimize for {model.__class__.__name__}. Using default parameters.")
        return model

    opt = BayesSearchCV(model, param_grid, n_iter=32, cv=3, n_jobs=-1, random_state=42)
    opt.fit(X_train, y_train)

    # Print the best hyperparameters and the best score
    print(f"Best hyperparameters for {model.__class__.__name__}: {opt.best_params_}")
    print(f"Best score for {model.__class__.__name__}: {opt.best_score_}")

    return opt.best_estimator_

# Optimize models
optimized_models = {}
for name, model in models.items():
    optimized_models[name] = bayesian_optimization(model, param_grids[name], X_train_80, y_train_80)

"""#Stacking Machine Learning"""

# Define base models
base_models = [
    ('Logistic Regression', optimized_models['Logistic Regression']),
    ('Random Forest', optimized_models['Random Forest']),
    ('Decision Tree', optimized_models['Decision Tree']),
    ('Naive Bayes', optimized_models['Naive Bayes']),
    ('Support Vector Machine', optimized_models['Support Vector Machine']),
    ('K-Nearest Neighbors', optimized_models['K-Nearest Neighbors']),
    ('XGBoost', optimized_models['XGBoost']),
    ('AdaBoost', optimized_models['AdaBoost'])
]

# Define meta-model
meta_model = RandomForestClassifier()

# Create stacking ensemble
stacking_clf = StackingClassifier(estimators=base_models, final_estimator=meta_model, cv=3)

# Train stacking ensemble
stacking_clf.fit(X_train_80, y_train_80)

print("Stacking ensemble trained")

"""#Evaluating Models"""

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=f'{model.__class__.__name__} (AUC = {auc:.2f})')

    return acc, prec, rec, f1, auc

# Evaluate models
results = {}
for name, model in optimized_models.items():
    results[name] = evaluate_model(model, X_test_80, y_test_80)
    print(f"\nResults for {name}:")
    print(f"Accuracy: {results[name][0]:.2f}")
    print(f"Precision: {results[name][1]:.2f}")
    print(f"Recall: {results[name][2]:.2f}")
    print(f"F1 Score: {results[name][3]:.2f}")
    print(f"AUC: {results[name][4]:.2f}")

# Fit GaussianNB directly since it has no hyperparameters to optimize
gnb = GaussianNB()
gnb.fit(X_train_80, y_train_80)
results['Naive Bayes'] = evaluate_model(gnb, X_test_80, y_test_80)
print(f"\nResults for Naive Bayes:")
print(f"Accuracy: {results['Naive Bayes'][0]:.2f}")
print(f"Precision: {results['Naive Bayes'][1]:.2f}")
print(f"Recall: {results['Naive Bayes'][2]:.2f}")
print(f"F1 Score: {results['Naive Bayes'][3]:.2f}")
print(f"AUC: {results['Naive Bayes'][4]:.2f}")

# Evaluate stacking model
results['Stacking Ensemble'] = evaluate_model(stacking_clf, X_test_80, y_test_80)
print(f"\nResults for Stacking Ensemble:")
print(f"Accuracy: {results['Stacking Ensemble'][0]:.2f}")
print(f"Precision: {results['Stacking Ensemble'][1]:.2f}")
print(f"Recall: {results['Stacking Ensemble'][2]:.2f}")
print(f"F1 Score: {results['Stacking Ensemble'][3]:.2f}")
print(f"AUC: {results['Stacking Ensemble'][4]:.2f}")

# Plot ROC curves
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves')
plt.legend(loc='lower right')
plt.show()

# Display results
results_df = pd.DataFrame({key: [value[0] * 100, value[1] * 100, value[2] * 100, value[3] * 100, value[4] * 100] for key, value in results.items()},
                          index=['Accuracy', 'Precision', 'Recall', 'F1 Score', 'AUC']).T
print(results_df.round(2))